### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by ximon18** [fabasoad/yaml-json-xml-converter-action#77]
**Describe the bug**
GitHub Actions prints a warning in the workflow summary and detailed log output when using this action.

**Steps to Reproduce**

Use this action.

**Expected behavior**

No warning should appear.

**Actual behavior**

This warning appears in the workflow run summary and detailed job output log:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Screenshots**

None.

**Technical information (please complete the following information):**

Reproduced using the latest fabasoad/yaml-json-xml-converter-action@v1.0.14.

**Additional context**

GitHub says:

> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

This project uses an older version of actions/core in `packages.json` so maybe this is as simple as bumping up to the newest version of actions/core as suggested by the GH Actions blog.

**Comment by fabasoad** [comment]
Hey @ximon18! Could you please try new `v1.1.0` version? The problem should be fixed there. Please let me know if not. Thanks.

**Comment by ximon18** [comment]
Thanks @fabasoad, will do as soon as I can and will post back here after.

**Comment by ximon18** [comment]
Thanks @fabasoad, that works for me!
